# Core functions for talking to EPM Cloud via epmautomate.bat
# Make sure to call Initialize-EPM before anything else, and always call
# Disconnect-EPM when done - orphaned sessions cause "too many sessions" errors.

Import-Module "$PSScriptRoot\EPMAutomate-Logging.psm1" -Force

$script:epmExe        = $null
$script:envCfg        = $null
$script:loggedIn      = $false
$script:lastExitCode  = 0      # tracks the last EPM exit code for scripts to use on exit

function Initialize-EPM {
    param(
        [string]$SettingsFile = "$PSScriptRoot\..\config\settings.json"
    )

    $cfg = Get-Content $SettingsFile -Raw | ConvertFrom-Json

    if (-not (Test-Path $cfg.epmAutomatePath)) {
        throw "epmautomate.bat not found at '$($cfg.epmAutomatePath)' - check settings.json"
    }

    $script:epmExe = $cfg.epmAutomatePath
    Write-Log "EPM Automate ready: $($script:epmExe)" "DEBUG"
}

function Import-EnvConfig {
    param(
        [string]$Env = "DEV"
    )

    $cfgPath = "$PSScriptRoot\..\config\environments\$($Env.ToLower()).json"

    if (-not (Test-Path $cfgPath)) {
        throw "No config found for environment '$Env' - expected: $cfgPath"
    }

    $script:envCfg = Get-Content $cfgPath -Raw | ConvertFrom-Json
    Write-Log "Loaded config for $Env ($($script:envCfg.serviceUrl))" "INFO"
    return $script:envCfg
}

function Connect-EPM {
    param([string]$Env = "DEV")

    if ($null -eq $script:envCfg) {
        Import-EnvConfig -Env $Env
    }

    $cfg = $script:envCfg

    # password file must be a .epw generated by: epmautomate encrypt <password> <key> <file>
    if (-not (Test-Path $cfg.passwordFile)) {
        throw "Password file not found: $($cfg.passwordFile) - run Encrypt-Password.ps1 first"
    }

    Write-Log "Logging in to $($cfg.serviceUrl)..." "INFO"

    & $script:epmExe login $cfg.username $cfg.passwordFile $cfg.serviceUrl $cfg.identityDomain
    if ($LASTEXITCODE -ne 0) {
        $script:lastExitCode = $LASTEXITCODE
        throw "Login failed (exit $LASTEXITCODE - $(Get-ExitMsg $LASTEXITCODE)) - check credentials in $Env config"
    }

    $script:loggedIn = $true
    Write-Log "Login OK" "OK"
}

function Disconnect-EPM {
    if (-not $script:loggedIn) { return }

    & $script:epmExe logout 2>$null
    $script:loggedIn = $false
    Write-Log "Logged out" "INFO"
}

function Invoke-EPM {
    # Runs any epmautomate command and returns a result object.
    # Stdout/stderr both captured - epmautomate sometimes writes errors to stdout.
    param(
        [string]$Cmd,
        [string[]]$CmdArgs = @()
    )

    if (-not $script:epmExe) {
        throw "EPM not initialized - call Initialize-EPM first"
    }

    Write-Log "epmautomate $Cmd $($CmdArgs -join ' ')" "DEBUG"

    $out = & $script:epmExe $Cmd @CmdArgs 2>&1
    $rc  = $LASTEXITCODE

    $script:lastExitCode = $rc

    $result = [PSCustomObject]@{
        Output   = ($out | Out-String).Trim()
        ExitCode = $rc
        OK       = ($rc -eq 0)
    }

    if (-not $result.OK) {
        Write-Log "Command failed (exit $rc - $(Get-ExitMsg $rc)): $($result.Output)" "ERROR"
    }

    return $result
}

function Get-ExitMsg {
    # Translates EPM Automate exit codes into human-readable descriptions.
    # Ref: https://docs.oracle.com/en/cloud/saas/enterprise-performance-management-common/cepma/epm_automate_status_codes.html
    param([int]$Code)

    switch ($Code) {
        0  { return "Success" }
        1  { return "Command failed - check privileges, resource names, or parameter values (HTTP 200/400)" }
        6  { return "Service unavailable or connection timed out - retry later (HTTP 404 / socket timeout)" }
        7  { return "Client error - invalid command, bad parameters, or file access issue" }
        9  { return "Authentication failed - check username, password file, and identity domain" }
        11 { return "Server error - service may be resetting or unavailable (HTTP 500/503)" }
        default { return "Unknown exit code $Code" }
    }
}

function Get-LastEPMExitCode {
    return $script:lastExitCode
}

Export-ModuleMember -Function Initialize-EPM, Import-EnvConfig, Connect-EPM, Disconnect-EPM,
                               Invoke-EPM, Get-ExitMsg, Get-LastEPMExitCode
